---

- block:
    - name: create local fonts directory
      ansible.builtin.file:
        path: "~{{ local_username }}/.local/share/fonts"
        state: directory
  become_user: "{{ local_username }}"

- block:
    - name: download nerd fonts to local fonts folder
      ansible.builtin.get_url:
        url: "{{ item  }}"
        dest: "~{{ local_username }}/.local/share/fonts/"
      with_items: "{{ terminal_customizations_nerd_fonts }}"
  become_user: "{{ local_username }}"

- name: refresh fonts cache
  ansible.builtin.shell: "fc-cache -fv"
  become_user: "{{ local_username }}"

# fix for https://github.com/gnunn1/tilix/wiki/VTE-Configuration-Issue using option 2
# also, set font to SourceCodePro+Powerline+Awesome Regular for tmux powerline
- block:
    - name: copy tilix config template
      ansible.builtin.copy:
        src: tilix.dconf
        dest: /tmp/tilix.dconf
        force: yes

    - name: import modified tilix config
      ansible.builtin.shell: dconf load /com/gexperts/Tilix/ < /tmp/tilix.dconf
      ignore_errors: yes
  become_user: "{{ local_username  }}"

# sample .tmux.conf file ready to use
- block:
    - name: check if .tmux.conf exists in user's home dir
      ansible.builtin.stat:
        path: "~{{ local_username }}/.tmux.conf"
      register: dottmuxdotconf

    - name: backup .tmux.conf if it exists
      ansible.builtin.copy:
        src: "~{{ local_username }}/.tmux.conf"
        dest: "~{{ local_username }}/.tmux.conf.orig"
      when: dottmuxdotconf.stat.exists

    - name: copy the sample .tmux.conf file
      ansible.builtin.copy:
        src: .tmux.conf
        dest: "~{{ local_username }}/.tmux.conf"
        force: yes
  become_user: "{{ local_username }}"

...
